### ISSUE TITLE
Tracking where diagnostics differ from the compiler

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-server#406]
Ongoing tracking issue for known areas where the diagnostics differ from the compiler.

### Places we don't show an error when there should be:
- [ ] Missing case branches 
- [ ] Unknown/missing exposed value in module exposing list
- [ ] Same value name imported from multiple modules. Ambiguous name

**Comment by peret** [comment]
Not sure if I should raise a separate issue for this, but using reserved words as field-/argument-names also isn't detected by the language server. E.g. elm compiler gives:
```
I am partway through parsing a record type, but I got stuck on this field name:

80|     { name : Maybe String
81|     , type : LocationType
          ^^^^
It looks like you are trying to use `type` as a field name, but that is a
reserved word. Try using a different name!
```

but elm-language-server doesn't show any errors.
